---
job: extension
config:
  name: "lora_alia_bhatt_consistent"
  process:
    - type: 'sd_trainer'
      training_folder: "/root/varunika/img/ai-toolkit/output"
      log_dir: "/root/varunika/img/ai-toolkit/output/lora_alia_bhatt_consistent/tensorboard"
      device: cuda:0
      trigger_word: null
      performance_log_every: 10

      network:
        type: "lora"
        linear: 32
        linear_alpha: 32
        lora_dropout: 0.0
        conv: 16
        conv_alpha: 16
        lokr_full_rank: true
        lokr_factor: -1
        
        network_kwargs:
          only_if_contains: 
            - ".*attn.*" 

      save:
        dtype: bf16 
        save_every: 250
        max_step_saves_to_keep: 4 
        save_format: diffusers
        push_to_hub: false 

      datasets:
        - folder_path: "/root/varunika/img/datasets/datasets/alia_bhatt" # UPDATE THIS
          control_path: null
          mask_path: null
          mask_min_value: 0.1
          trigger_token: '[AB]'
          initializer_concept: "A 34 year old Indian woman, 5 feet 1 inch tall, fair skin, slim build, slim jawline, dimples on cheeks"
          default_caption: ''
          caption_ext: txt
          caption_dropout_rate: 0
          cache_latents_to_disk: false
          is_reg: false
          network_weight: 1
          resolution:
          - 512
          - 768
          - 1024
          controls: []
          shrink_video_to_frames: true
          num_frames: 1
          do_i2v: true

      train:
        batch_size: 1 # OOM Fix
        bypass_guidance_embedding: false
        steps: 7000
        gradient_accumulation: 2 # OOM Fix
        train_unet: true 
        train_text_encoder: false
        gradient_checkpointing: true 
        noise_scheduler: flowmatch
        optimizer: adamw8bit # OOM Fix
        timestep_type: weighted
        content_or_style: balanced
        optimizer_params:
          weight_decay: 0.0001
        enable_ti: true
        enable_ttb: false
        unload_text_encoder: false
        cache_text_embeddings: false
        lr: 0.0001
        ema_config:
          use_ema: false
          ema_decay: 0.99
        skip_first_sample: false
        disable_sampling: false
        dtype: bf16
        diff_output_preservation: false
        diff_output_preservation_multiplier: 1
        diff_output_preservation_class: person

      model:
        name_or_path: "Qwen/Qwen-Image" 
        quantize: false
        qtype: qfloat8
        quantize_te: false
        qtype_te: qfloat8
        arch: qwen_image
        low_vram: false
        model_kwargs: {}

      sample:
        sampler: flowmatch
        sample_every: 250
        width: 1664
        height: 928
        samples:
          - prompt: "A close-up portrait of ([AB] woman) smiling, soft natural light, bokeh background."
          - prompt: "A full-body shot of ([AB] woman) walking in a bustling city street, vibrant atmosphere."
        neg: ''
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 25
        num_frames: 1
        fps: 1

meta:
  name: "lora_alia_bhatt_consistent"
  version: '1.0'