---
job: extension
config:
  name: "lora_alia_bhatt_baseline"
  process:
    - type: 'sd_trainer'
      training_folder: "/root/varunika/img/ai-toolkit/output"
      log_dir: "/root/varunika/img/ai-toolkit/output/lora_alia_bhatt_baseline/tensorboard" 
      device: cuda:0 
      performance_log_every: 10

      network:
        type: "lora"
        linear: 32 
        linear_alpha: 32
        lora_dropout: 0.0         
        network_kwargs:
          only_if_contains: 
            - ".*attn.*" 

      save:
        dtype: bf16 
        save_every: 250
        max_step_saves_to_keep: 4 
        save_format: diffusers
        push_to_hub: false 

      datasets:
        - folder_path: "/root/varunika/img/datasets/datasets/alia_bhatt" 
          trigger_token: '[AB]'
          initializer_concept: "A 34 year old Indian woman, 5 feet 1 inch tall, fair skin, slim build, slim jawline, dimples on cheeks"
          caption_ext: txt
          cache_latents_to_disk: false
          resolution:
          - 512
          - 768
          - 1024

      train:
        batch_size: 1
        steps: 2000
        gradient_accumulation: 2
        train_unet: true 
        train_text_encoder: false
        gradient_checkpointing: true 
        noise_scheduler: flowmatch
        optimizer: adamw8bit 
        lr: 0.0001
        ema_config:
          use_ema: false
        dtype: bf16

      model:
        name_or_path: "Qwen/Qwen-Image" 
        quantize: false
        arch: qwen_image

      sample:
        sampler: flowmatch
        sample_every: 250
        width: 1664
        height: 928
        prompts:
          - "A close-up portrait of ([AB] woman) smiling, soft natural light, bokeh background."
          - "A full-body shot of ([AB] woman) walking in a bustling city street, vibrant atmosphere."
        neg: ''
        seed: 42
        guidance_scale: 4
        sample_steps: 25

meta:
  name: "lora_alia_bhatt_baseline" 
  version: '1.0'